FASTA_VECTOR_LIB_NAME = fastaVector
FASTA_VECTOR_MAJOR_VERSION = 1
FASTA_VECTOR_MINOR_VERSION = 0
FASTA_VECTOR_VERSION = $(FASTA_VECTOR_MAJOR).$(FASTA_VECTOR_MINOR_VERSION)

CC = gcc
CFLAGS 		= -std=c11 -Wall -mtune=native -O3 -fPIC
LDFLAGS_SHARED_LIB = -shared
SHARED_LIB_FILE_EXTENSION = .so
SHARED_LIB_FILE_EXTENSION_MAC = .dylib
STATIC_LIB_FILE_EXTENSION = .a
HEADER_FILE_EXTENSION = .h

FASTA_VECTOR_BUILD_DIR = ./build/
FASTA_VECTOR_SRC_DIR = ./src/

ifeq ($(PREFIX),)
PREFIX := /usr/local
endif


FASTA_VECTOR_PROJECT_HEADER_SRC = $(FASTA_VECTOR_SRC_DIR)/fastaVector.h

FASTA_VECTOR_STATIC_LIB_BUILD_SRC = $(FASTA_VECTOR_BUILD_DIR)$(FASTA_VECTOR_LIB_NAME)$(STATIC_LIB_FILE_EXTENSION)
FASTA_VECTOR_SHARED_LIB_BUILD_SRC = $(FASTA_VECTOR_BUILD_DIR)$(FASTA_VECTOR_LIB_NAME)$(SHARED_LIB_FILE_EXTENSION)
FASTA_VECTOR_SHARED_LIB_MAC_BUILD_SRC = $(FASTA_VECTOR_BUILD_DIR)$(FASTA_VECTOR_LIB_NAME)$(SHARED_LIB_FILE_EXTENSION_MAC)

FASTA_VECTOR_INSTALL_DIR = $(DESTDIR)$(PREFIX)
FASTA_VECTOR_INSTALL_LIB_DIR = $(FASTA_VECTOR_INSTALL_DIR)/lib/
FASTA_VECTOR_INSTALL_INCLUDE_DIR = $(FASTA_VECTOR_INSTALL_DIR)/include/
FASTA_VECTOR_INSTALL_HEADER_SRC = $(FASTA_VECTOR_INSTALL_INCLUDE_DIR)$(FASTA_VECTOR_LIB_NAME)$(HEADER_FILE_EXTENSION)
FASTA_VECTOR_INSTALL_STATIC_LIB_SRC = $(FASTA_VECTOR_INSTALL_LIB_DIR)$(FASTA_VECTOR_LIB_NAME)$(STATIC_LIB_FILE_EXTENSION)
FASTA_VECTOR_INSTALL_SHARED_LIB_SRC = $(FASTA_VECTOR_INSTALL_LIB_DIR)$(FASTA_VECTOR_LIB_NAME)$(SHARED_LIB_FILE_EXTENSION)
FASTA_VECTOR_INSTALL_SHARED_LIB_MAC_SRC = $(FASTA_VECTOR_INSTALL_LIB_DIR)$(FASTA_VECTOR_LIB_NAME)$(SHARED_LIB_FILE_EXTENSION_MAC)

BUILD_LIB_TARGETS = $(FASTA_VECTOR_STATIC_LIB_BUILD_SRC) $(FASTA_VECTOR_SHARED_LIB_BUILD_SRC) $(FASTA_VECTOR_SHARED_LIB_MAC_BUILD_SRC)
INSTALL_LIB_TARGETS = $(PREFIX)

SRCS := $(shell find $(FASTA_VECTOR_SRC_DIR) -name *.c)
OBJS := $(SRCS:%=$(FASTA_VECTOR_BUILD_DIR)/%.o)



$(BUILD_DIR)/%.c.o: %.c
	$(MKDIR_P) $(dir $@)
ifeq ($(ARCH), MAC)
	$(CC) $(CFLAGS) $(CFLAGS_MAC_M1) -c $< -o $@
else
	$(CC) $(CFLAGS) $(CFLAGS) -c $< -o $@
endif


.PHONY: shared
shared: $(OBJS)
	$(CC) -o $(FASTA_VECTOR_SHARED_LIB_MAC_BUILD_SRC) $(LDFLAGS_SHARED_LIB) $(OBJS)
endif

.PHONY: static
static: $(OBJS)
	ar rcs $(FASTA_VECTOR_STATIC_LIB_BUILD_SRC) $(OBJS)

.PHONY: clean
clean:
	$(RM) $(BUILD_LIB_TARGETS) $(OBJS)

.PHONY: install
install:
	mkdir $(FASTA_VECTOR_INSTALL_LIB_DIR)
	mkdir $(FASTA_VECTOR_INSTALL_INCLUDE_DIR)
	cp $(FASTA_VECTOR_PROJECT_HEADER_SRC) $(FASTA_VECTOR_INSTALL_HEADER_SRC)
	cp $(FASTA_VECTOR_STATIC_LIB_BUILD_SRC) $(FASTA_VECTOR_INSTALL_STATIC_LIB_SRC)
	cp $(FASTA_VECTOR_SHARED_LIB_BUILD_SRC) $(FASTA_VECTOR_INSTALL_SHARED_LIB_SRC)
	cp $(FASTA_VECTOR_SHARED_LIB_MAC_BUILD_SRC) $(FASTA_VECTOR_INSTALL_SHARED_LIB_MAC_SRC)


.PHONY: uninstall
uninstall:
	rm -f $(FASTA_VECTOR_INSTALL_HEADER_SRC)
	rm -f $(FASTA_VECTOR_INSTALL_STATIC_LIB_SRC)
	rm -f $(FASTA_VECTOR_INSTALL_SHARED_LIB_SRC)
	rm -f $(FASTA_VECTOR_INSTALL_SHARED_LIB_MAC_SRC)
