name: Build and Test

on: [push, pull_request]

jobs:
  check-build:
    runs-on: ubuntu-20.04
    container:
      image: traviswheelerlab/fastavector-build
      volumes:
        - ${{ github.workspace }}:/code
    steps:
      - uses: actions/checkout@v1
      - run: cmake .
      - run: make
  
  check-build-mac:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v1
      - run: cmake -DCMAKE_C_COMPILER=`which gcc-10` .
      - run: make
  
  check-legacy-build:
    runs-on: ubuntu-20.04
    container:
      image: traviswheelerlab/fastavector-build
      volumes:
        - ${{ github.workspace }}:/code
    steps:
      - uses: actions/checkout@v1
      - run: make -f Makefile_legacy
      - run: make -f Makefile_legacy static
  
  check-legacy-build-mac:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v1
      - run: make -f Makefile_legacy CC=`which gcc-10`
      - run: make -f Makefile_legacy static CC=`which gcc-10`

  check-tests:
    runs-on: ubuntu-20.04
    container:
      image: traviswheelerlab/fastavector-build
      volumes:
        - ${{ github.workspace }}:/code
    steps:
      - uses: actions/checkout@v1
      - run: cmake .
      - run: make
      - run: make test

  run-format:
    runs-on: ubuntu-20.04
    container:
      image: traviswheelerlab/fastavector-build
      volumes:
        - ${{ github.workspace }}:/code
    steps:
      - uses: actions/checkout@v2
      - name: Run formatter
        run: ./tool/run-format.sh
      - name: Push back to branch
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add src/
          git commit -m "Format code"
          git push

  check-format:
    needs: run-format
    runs-on: ubuntu-20.04
    container:
      image: traviswheelerlab/fastavector-build
      volumes:
        - ${{ github.workspace }}:/code
    steps:
      - uses: actions/checkout@v1
      - run: ./tool/check-format.sh

